name: CI

on:
  push:
    branches: [ main ]

jobs:
  generate-client-sdk:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        planguage: 
          - name: "csharp"
            generator: csharp

          - name: typescript
            generator: typescript-axios

          - name: python 
            generator: python 
    steps:
      - name: ⚙️ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔎 Debug Working Directory Contents
        run: |
          echo "PWD:"
          pwd
          echo "ROOT FILES:"
          ls -la
          echo "SEARCH CONFIG FILE:"
          find . -name "openapi-${{ matrix.planguage.name }}-config.json"

      - name: 🐳 Run OpenAPI Generator CLI for ${{ matrix.planguage.name }}
        uses: docker://openapitools/openapi-generator-cli:v7.8.0
        with:
          args: >
            generate
            -i /github/workspace/specs/yaml/tenants-v1-swagger.yaml
            -g ${{ matrix.planguage.generator }}                  
            -o /github/workspace/sdks/${{ matrix.planguage.name }}
            -c /github/workspace/sdk-generation-configuration/openapi-${{ matrix.planguage.name }}-config.json
            --skip-validate-spec
      - name: List all files in Current Directory
        run: |
          ls 
          cd sdks
          ls
        