name: CI

on:
  push:
    branches: [ main ]

permissions: 
  contents: write

jobs:
  update-version-and-commit: 
    uses: './.github/workflows/update-version-and-commit.yaml'
    if: github.actor != 'github-actions[bot]'

  generate-client-sdk:
    needs: update-version-and-commit
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        planguage: 
          - name: "csharp"
            generator: csharp

        #  - name: typescript
        #    generator: typescript-axios

        #  - name: python 
        #    generator: python 
    steps:
      - name: ⚙️ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print Config file
        run:  jq . ./sdk-generation-configuration/openapi-csharp-config.json

      - name: Clone ${{ matrix.planguage.name }} SDK Repository
        env:
          TOKEN: ${{ secrets.SDK_PUBLISHER_TOKEN }}
        run: |
          git clone https://$TOKEN@github.com/EdGraph-OSS/${{ matrix.planguage.name }}-sdk target
          cd target
          rm -rf ./src

      - name: 🔎 Debug Working Directory Contents
        run: |
          echo "PWD:"
          pwd
          echo "ROOT FILES:"
          ls -la
          echo "SEARCH CONFIG FILE:"
          find . -name "openapi-${{ matrix.planguage.name }}-config.json"

      - name: 🐳 Run OpenAPI Generator CLI for ${{ matrix.planguage.name }}
        uses: docker://openapitools/openapi-generator-cli:v7.8.0
        with:
          args: >
            generate
            -i /github/workspace/specs/yaml/tenants-v1-swagger.yaml
            -g ${{ matrix.planguage.generator }}                  
            -o /github/workspace/target/src/
            -c /github/workspace/sdk-generation-configuration/openapi-${{ matrix.planguage.name }}-config.json
            --skip-validate-spec

      - name: List all files in Current Directory
        run: |
          ls 
          cd target
          ls

      - name: Generate file
        run: |
          cd target
          touch ${{ matrix.planguage.name }}-file.yaml

      - name: Commit & Push to ${{ matrix.planguage.name }} SDK Repository
        run: | 
          cd target 
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git add .
          git commit -m "Generate SDK"
          git pull origin main --no-rebase --allow-unrelated-histories
          git push origin main
        